export const I_GOT_SOCKET_ID = 'I GOT A SOCKET ID.';
export const I_CALL_SOMEBODY = 'I CALL SOMEBODY.';
export const SOMEBODY_CALLS_ME = 'SOMEBODY CALLS ME.';
export const I_ANSWER_THE_CALL = 'I ANSWER THE CALL.';
export const MY_CALL_IS_ACCEPTED = 'MY CALL IS ACCEPTED.';
export const JOIN_MEETING = 'JOIN_MEETING';
// こっから下は、client側でのみsocket eventを作っている。
export const I_GOT_OTHER_USERS_INFO = 'I_GOT_OTHER_USERS_INFO';
export const PARTICIPANT_IS_SENDING_SIGNAL_TO_OTHER_USERS = 'PARTICIPANT_IS_SENDING_TO_OTHER_USERS';
export const NEW_USER_JOINED = 'NEW_USER_JOINED';
export const I_ACCEPT_A_PARTICIPANT_AND_SEND_A_SIGNAL = 'I_ACCEPT_A_PARTICIPANT_AND_SEND_A_SIGNAL';
// export const OTHER_USERS_ARE_RETURNING_SIGNAL = 'OTHER_USERS_ARE_RETURNING_SIGNAL';
export const I_GOT_A_RETURN_SIGNAL_FROM_PEER = 'I_GOT_A_RETURN_SIGNAL_FROM_PEER';
