export const I_GOT_SOCKET_ID = 'I GOT A SOCKET ID.';
export const I_CALL_SOMEBODY = 'I CALL SOMEBODY.';
export const SOMEBODY_CALLS_ME = 'SOMEBODY CALLS ME.';
export const I_ANSWER_THE_CALL = 'I ANSWER THE CALL.';
export const MY_CALL_IS_ACCEPTED = 'MY CALL IS ACCEPTED.';
export const SORRY_I_DONT_WANNA_CHAT_WITH_YOU = 'SORRY_I_DONT_WANNA_CHAT_WITH_YOU';
export const MY_CALL_IS_REJECTED = 'MY_CALL_WAS_REJECTED';
export const JOIN_MEETING = 'JOIN_MEETING';
// こっから下は、client側でのみsocket eventを作っている。
export const I_GOT_OTHER_USERS_INFO = 'I_GOT_OTHER_USERS_INFO';
export const PARTICIPANT_IS_SENDING_SIGNAL_TO_OTHER_USERS = 'PARTICIPANT_IS_SENDING_TO_OTHER_USERS';
export const NEW_USER_JOINED = 'NEW_USER_JOINED';
export const I_ACCEPT_A_PARTICIPANT_AND_SEND_A_SIGNAL = 'I_ACCEPT_A_PARTICIPANT_AND_SEND_A_SIGNAL';
// export const OTHER_USERS_ARE_RETURNING_SIGNAL = 'OTHER_USERS_ARE_RETURNING_SIGNAL';
export const I_GOT_A_RETURN_SIGNAL_FROM_PEER = 'I_GOT_A_RETURN_SIGNAL_FROM_PEER';

// conversationに関して
export const I_SEND_CONVERSATION_ID_TO_MY_PARTNER = 'I_SEND_CONVERSATION_ID_TO_MY_PARTNER';
export const MY_CALLED_USER_CREATED_CONVERSATION = 'MY_CALLED_USER_CREATED_CONVERSATION';

export const I_WANNA_SWITCH_CURRENT_LANGUAGE = 'I_WANNA_SWITCH_TO_MY_LEARNING_LANGUAGE';
export const MY_PARTNER_WANNA_SWITCH_CURRENT_LANGUAGE = 'MY_PARTNER_WANNA_SWITCH_LANGUAGE';

// integratedUserMediaに関して
export const I_SEND_INTEGRATED_USER_MEDIA_ID_TO_MY_PARTNER = 'I_SEND_INTEGRATED_USER_MEDIA_ID_TO_MY_PARTNER';
export const MY_CALLED_USER_CREATED_INTEGRATED_USER_MEDIA = 'MY_CALLED_USER_CREATED_INTEGRATED_USER_MEDIA';

// subtitle
export const I_REQUEST_PARTNERS_VOICE_TEXT = 'I_REQUEST_YOUR_VOICE_TEXT';
export const MY_PARTENER_REQUESTS_MY_VOICE_TEXT = 'MY_PARTENER_REQUESTS_MY_VOICE_TEXT';
export const I_SEND_MY_VOICE_TEXT_TO_MY_PARTNER = 'I_SEND_MY_VOICE_TEXT_TO_MY_PARTNER';
export const MY_PARTNER_SEND_VOICE_TEXT_TO_ME = 'MY_PARTNER_SEND_VOICE_TEXT_TO_ME';

export const I_SEND_MY_INTERIM_TRANSCRIPT_TO_MY_PARTNER = 'I_SEND_MY_INTERIM_TRANSCRIPT_TO_MY_PARTNER';
export const I_SEND_MY_FINAL_TRANSCRIPT_TO_MY_PARTNER = 'I_SEND_MY_FINAL_TRANSCRIPT_TO_MY_PARTNER';
export const MY_PARTNER_SEND_ME_INTERIM_TRANSCRIPT = 'MY_PARTNER_SEND_ME_INTERIM_TRANSCRIPT';
export const MY_PARTNER_SEND_ME_FINAL_TRANSCRIPT = 'MY_PARTNER_SEND_ME_FINAL_TRANSCRIPT';

// chat
export const I_SEND_CHAT_MESSAGE_TO_MY_PARTNER = 'I_SEND_CHAT_MESSAGE_TO_MY_PARTNER';
export const MY_PARTNER_SEND_ME_A_CHAT_MESSAGE = 'MY_PARTNER_SEND_ME_A_CHAT_MESSAGE';

// mediaRecorderに関して、、、call終わった後。
export const OUR_BLOB_SIZE_SHOULD_BE_THIS = 'OUR_BLOB_SIZE_SHOULD_BE_THIS';
export const I_GOT_BLOB_SIZE_FROM_MY_PARTNER = 'I_GOT_BLOB_SIZE_FROM_MY_PARTNER';
